name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macOS-12
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 12"
    
    steps:
      - uses: actions/checkout@v2
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme Extendable-Package -destination "${{ matrix.destination }}" test | xcpretty
